/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#2f3131",
        "surface-container-lowest": "#0d0e0d",
        "primary-fixed": "#e3e2df",
        "secondary-fixed": "#e2e2e2",
        "primary-container": "#e3e2df",
        "surface": "#131413",
        "surface-container": "#1f201f",
        "background": "#131413",
        "on-surface-variant": "#c5c7c1",
        "on-primary-fixed-variant": "#464744",
        "outline-variant": "#454843",
        "on-secondary-fixed": "#1a1c1c",
        "on-tertiary-fixed": "#3b0900",
        "surface-container-high": "#292a29",
        "tertiary": "#ffffff",
        "secondary-fixed-dim": "#c6c6c7",
        "surface-variant": "#343534",
        "on-surface": "#e4e2e0",
        "on-tertiary-fixed-variant": "#872000",
        "on-primary-fixed": "#1b1c1a",
        "tertiary-container": "#ffdbd1",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#30312f",
        "inverse-surface": "#e4e2e0",
        "on-tertiary": "#601400",
        "secondary-container": "#454747",
        "surface-tint": "#c7c7c3",
        "tertiary-fixed-dim": "#ffb5a0",
        "surface-bright": "#393938",
        "outline": "#8f918c",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#454747",
        "on-primary-container": "#646562",
        "on-primary": "#2f312e",
        "secondary": "#c6c6c7",
        "error": "#ffb4ab",
        "tertiary-fixed": "#ffdbd1",
        "surface-container-highest": "#343534",
        "on-secondary-container": "#b4b5b5",
        "on-background": "#e4e2e0",
        "primary-fixed-dim": "#c7c7c3",
        "inverse-primary": "#5e5f5c",
        "primary": "#ffffff",
        "surface-dim": "#131413",
        "surface-container-low": "#1b1c1b",
        "on-tertiary-container": "#bc3000",
        "brand-orange": "#FF4500",
      },
      borderRadius: {
        "DEFAULT": "0rem",
        "lg": "0rem",
        "xl": "0rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "margin": "2rem",
        "gutter": "1.5rem",
        "space-xl": "3rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-gutter": "1.5rem"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "label-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "headline": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "30px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-lg": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-sm": ["10px", { "lineHeight": "14px", "letterSpacing": "0.08em", "fontWeight": "500" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "52px", "letterSpacing": "-0.03em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
};
